# Generated by Django 3.1.1 on 2020-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_last_opened_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_opened_chat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
