# Generated by Django 3.1.1 on 2020-11-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_last_opened_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_opened_chat',
        ),
    ]
