# Generated by Django 3.1.1 on 2020-09-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20200923_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
