# Generated by Django 3.1.1 on 2020-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_auto_20200923_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
