# Generated by Django 3.1.1 on 2020-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
