# Generated by Django 3.1.1 on 2020-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_auto_20201002_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/community_thumbnails/start-up.svg', upload_to='community_thumbnails'),
        ),
    ]
