# Generated by Django 3.1.1 on 2020-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_auto_20201002_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='thumbnail',
            field=models.ImageField(blank=True, default='community_thumbnails/rocket (1).png', upload_to='community_thumbnails'),
        ),
    ]
