# Generated by Django 3.1.1 on 2020-10-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_auto_20201002_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_group', to='forum.community'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='posts',
            field=models.ManyToManyField(related_name='group_posts', to='forum.Post'),
        ),
    ]
