# Generated by Django 3.1.1 on 2020-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0039_auto_20201005_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
