# Generated by Django 3.1.1 on 2020-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0040_auto_20201005_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trending_points',
            field=models.IntegerField(default=0),
        ),
    ]
