# Generated by Django 3.1.1 on 2020-10-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0044_auto_20201018_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
    ]
