# Generated by Django 3.1.1 on 2020-10-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0047_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_parents', to='forum.comment'),
        ),
    ]
