# Generated by Django 3.1.1 on 2020-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0048_comment_reply_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
