# Generated by Django 3.1.1 on 2020-11-18 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0057_messagenotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageNotification',
            new_name='ChatNotification',
        ),
    ]
