# Generated by Django 3.1.1 on 2020-11-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_recipient'),
        ('forum', '0059_chatnotification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnotification',
            name='chat_room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
