# Generated by Django 3.1.1 on 2020-12-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_recipient'),
        ('forum', '0062_auto_20201204_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotification',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_alerts', to='chat.chatroom'),
        ),
    ]
