# Generated by Django 3.1.1 on 2020-11-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201113_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
