# Generated by Django 3.1.1 on 2020-11-15 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chatroom_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_starter', to='auth.user'),
            preserve_default=False,
        ),
    ]
