# Generated by Django 3.1.1 on 2020-11-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20201115_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to='auth.user'),
            preserve_default=False,
        ),
    ]
